name: Deploy KeyBot

on:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: (Optional) Initialize SQLite DB
        run: |
          python - << 'EOF'
          import sqlite3
          conn = sqlite3.connect('keys.db')
          conn.execute('''
            CREATE TABLE IF NOT EXISTS keys (
              key TEXT PRIMARY KEY,
              role_id INTEGER,
              redeemed_by INTEGER,
              redeemed_at TEXT
            );
          ''')
          conn.commit()
          EOF

      - name: Launch KeyBot
        env:
          DISCORD_TOKEN:    ${{ secrets.DISCORD_TOKEN }}
          OWNER_ID:         ${{ secrets.OWNER_ID }}
          ADMIN_ROLE_NAME:  ${{ secrets.ADMIN_ROLE_NAME }}
          KEYS_GIST_TOKEN:  ${{ secrets.KEYS_GIST_TOKEN }}
          GIST_ID:          ${{ secrets.GIST_ID }}
          HMAC_SECRET:      ${{ secrets.HMAC_SECRET }}
        run: python key_system_bot.py
